# SUNSPOT


In [1]:
import pandas as pd
import numpy as np #deal array
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import matplotlib.pyplot as plt

In [18]:
data=pd.read_csv("C:/Users/Milan saji/Downloads/Sunspots.csv",index_col='Date',parse_dates=True)

In [19]:
data

Unnamed: 0  Monthly Mean Total Sunspot Number
Date                                                     
1749-01-31           0                               96.7
1749-02-28           1                              104.3
1749-03-31           2                              116.7
1749-04-30           3                               92.8
1749-05-31           4                              141.7
...                ...                                ...
2020-09-30        3260                                0.6
2020-10-31        3261                               14.4
2020-11-30        3262                               34.0
2020-12-31        3263                               21.8
2021-01-31        3264                               10.4

[3265 rows x 2 columns]

In [20]:
data.head(10)

Unnamed: 0  Monthly Mean Total Sunspot Number
Date                                                     
1749-01-31           0                               96.7
1749-02-28           1                              104.3
1749-03-31           2                              116.7
1749-04-30           3                               92.8
1749-05-31           4                              141.7
1749-06-30           5                              139.2
1749-07-31           6                              158.0
1749-08-31           7                              110.5
1749-09-30           8                              126.5
1749-10-31           9                              125.8

In [21]:
data.tail(10)

Unnamed: 0  Monthly Mean Total Sunspot Number
Date                                                     
2020-04-30        3255                                5.2
2020-05-31        3256                                0.2
2020-06-30        3257                                5.8
2020-07-31        3258                                6.1
2020-08-31        3259                                7.5
2020-09-30        3260                                0.6
2020-10-31        3261                               14.4
2020-11-30        3262                               34.0
2020-12-31        3263                               21.8
2021-01-31        3264                               10.4

In [22]:
data.shape

(3265, 2)

In [23]:
data.nunique()

Unnamed: 0                           3265
Monthly Mean Total Sunspot Number    1599
dtype: int64

In [24]:
#scale to 0 nd 1
Scaler=MinMaxScaler(feature_range=(0,1))


In [26]:
#transform data
data=Scaler.fit_transform(data).flatten()

In [27]:
data

array([0.00000000e+00, 2.42842793e-01, 3.06372549e-04, ...,
       5.47463586e-02, 1.00000000e+00, 2.61175289e-02])

In [28]:
#transformed is splitted
train=data[:2500]
test=data[2500:]

In [29]:
train

array([0.00000000e+00, 2.42842793e-01, 3.06372549e-04, ...,
       1.95630337e-01, 3.82659314e-01, 2.04671020e-01])

In [30]:
test


array([0.38296569, 0.17980914, 0.38327206, ..., 0.05474636, 1.        ,
       0.02611753])

In [32]:
#going to create time series generator, there is input and features
from keras.preprocessing.sequence import TimeseriesGenerator


In [180]:
#input can be any
n_input=7
n_features=1
generatortrain=TimeseriesGenerator(train,train,length=n_input,batch_size=1)
generatortest=TimeseriesGenerator(test,test,length=n_input,batch_size=1)


In [181]:
#give answer
generatortrain[20]

(array([[0.37879306, 0.40001978, 0.43746048, 0.41583516, 0.41583516,
         0.39645907, 0.44251869]]),
 array([0.39396528]))

In [182]:
generatortest[2800]
#model is made

(array([[0.09916621, 0.09973295, 0.12824041, 0.09814106, 0.09814106,
         0.10082094, 0.13147618]]),
 array([0.10148989]))

In [183]:
#making sequential model using simprnn,lstm,gru(imporrt)
from keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,LSTM,GRU,Dense
import math


In [184]:
#tanh in time series,
model=Sequential()
model.add(SimpleRNN(units=100,input_shape=(n_input,n_features),activation='tanh'))
model.add(Dense(units=5,activation='tanh'))


In [185]:
model.summary()


Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_11 (SimpleRNN)   (None, 100)               10200     
                                                                 
 dense_12 (Dense)            (None, 5)                 505       
                                                                 
Total params: 10705 (41.82 KB)
Trainable params: 10705 (41.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [186]:

model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [187]:
model.fit(generatortrain,epochs=2)
#y=output(class/labl)

Epoch 1/2
2493/2493 [==============================] - 15s 5ms/step - loss: 9.4786e-04 - accuracy: 0.0000e+00
Epoch 2/2
2493/2493 [==============================] - 13s 5ms/step - loss: 5.4811e-04 - accuracy: 0.0000e+00


In [188]:
model.evaluate(generatortest)

8569/8569 [==============================] - 45s 5ms/step - loss: 3.5245e-04 - accuracy: 0.0000e+00


[0.0003524456697050482, 0.0]

In [78]:
model.predict(generatortest)

4023/4023 [==============================] - 17s 4ms/step


array([[ 0.14768904,  0.13445236,  0.16144097,  0.14613344,  0.15519193],
       [ 0.39888987,  0.40878934,  0.38750172,  0.39768812,  0.3972009 ],
       [ 0.16188821,  0.15263303,  0.17251329,  0.16061504,  0.17106614],
       ...,
       [-0.08165245, -0.12442166, -0.01077398, -0.07396775, -0.04364377],
       [ 0.7779354 ,  0.7947144 ,  0.76021904,  0.775064  ,  0.7722635 ],
       [-0.09159589, -0.13405135, -0.01882803, -0.08607635, -0.05473014]],
      dtype=float32)

# USING NIFTY

In [135]:
import pandas as pd
import numpy as np #deal array
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import matplotlib.pyplot as plt

In [136]:
data=pd.read_csv("C:/Users/Milan saji/Downloads/NIFTY.csv",index_col='Date',parse_dates=True)

In [137]:
data

Open    High      Low  Turnover
Date                                          
02-03-2009  43.1900  43.380  41.4400   43.1700
03-03-2009  43.1700  43.900  41.2000   43.8900
04-03-2009  43.8900  43.890  42.1600   42.5200
05-03-2009  42.5200  42.710  40.4100   41.4900
06-03-2009  41.4900  41.490  37.5700   38.1600
...             ...     ...      ...       ...
04-05-2020  33.9875  43.920  33.9875   43.6700
05-05-2020  43.6700  43.865  38.1475   43.6075
06-05-2020  43.6075  43.630  40.1975   41.2475
07-05-2020  41.2475  41.715  39.6575   39.9300
08-05-2020  39.9300  39.930  36.5475   38.4075

[2769 rows x 4 columns]

In [138]:
#scale to 0 nd 1
Scaler=MinMaxScaler(feature_range=(0,1))


In [139]:
#transform data ,in nifty we no need to flatten
data=Scaler.fit_transform(data).flatten()

In [140]:
#transformed is splitted
train=data[:2500]
test=data[2500:]

In [141]:
train

array([0.44754647, 0.42956052, 0.4862573 , ..., 0.2597013 , 0.26860565,
       0.24894068])

In [142]:
test

array([0.24894068, 0.23688635, 0.27738312, ..., 0.38406251, 0.41347119,
       0.38217605])

In [143]:
#going to create time series generator, there is input and features
from keras.preprocessing.sequence import TimeseriesGenerator


In [144]:
#input can be any
n_input=7
n_features=1
generatortrain=TimeseriesGenerator(train,train,length=n_input,batch_size=1)
generatortest=TimeseriesGenerator(test,test,length=n_input,batch_size=1)


In [145]:
#give answer
generatortrain[20]

(array([[0.37879306, 0.40001978, 0.43746048, 0.41583516, 0.41583516,
         0.39645907, 0.44251869]]),
 array([0.39396528]))

In [146]:
generatortest[2800]
#model is made

(array([[0.09916621, 0.09973295, 0.12824041, 0.09814106, 0.09814106,
         0.10082094, 0.13147618]]),
 array([0.10148989]))

In [147]:
#making sequential model using simprnn,lstm,gru(imporrt)
from keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN,LSTM,GRU,Dense
import math


In [148]:
#tanh in time series,
model=Sequential()
model.add(SimpleRNN(units=100,input_shape=(n_input,n_features),activation='tanh'))
model.add(Dense(units=5,activation='tanh'))


In [149]:
model.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_9 (SimpleRNN)    (None, 100)               10200     
                                                                 
 dense_7 (Dense)             (None, 5)                 505       
                                                                 
Total params: 10705 (41.82 KB)
Trainable params: 10705 (41.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [150]:

model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [151]:
model.fit(generatortrain,epochs=2)
#y=output(class/labl)

Epoch 1/2
2493/2493 [==============================] - 14s 5ms/step - loss: 8.2637e-04 - accuracy: 0.0000e+00
Epoch 2/2
2493/2493 [==============================] - 12s 5ms/step - loss: 5.6841e-04 - accuracy: 0.0000e+00


In [152]:
model.evaluate(generatortest)

8569/8569 [==============================] - 37s 4ms/step - loss: 6.3679e-04 - accuracy: 2.3340e-04


[0.0006367852329276502, 0.00023339946346823126]

In [153]:
model.predict(generatortest)

8569/8569 [==============================] - 36s 4ms/step


array([[0.25110695, 0.25386623, 0.2506259 , 0.2508194 , 0.25359833],
       [0.23805258, 0.23885371, 0.2395021 , 0.23725116, 0.24093722],
       [0.2512638 , 0.2522264 , 0.25077972, 0.249917  , 0.2520697 ],
       ...,
       [0.42527884, 0.42659196, 0.42374957, 0.42213768, 0.42653722],
       [0.4295734 , 0.42861176, 0.42994443, 0.42843488, 0.4298995 ],
       [0.40036464, 0.40364355, 0.3987026 , 0.398431  , 0.40327403]],
      dtype=float32)

# USING LSTM


In [155]:
#tanh in time series,
model=Sequential()
model.add(LSTM(units=100,input_shape=(n_input,n_features),activation='tanh'))
model.add(Dense(units=5,activation='tanh'))


In [156]:
model.summary()


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 100)               40800     
                                                                 
 dense_8 (Dense)             (None, 5)                 505       
                                                                 
Total params: 41305 (161.35 KB)
Trainable params: 41305 (161.35 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [157]:

model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [158]:
model.fit(generatortrain,epochs=2)
#y=output(class/labl)

Epoch 1/2
2493/2493 [==============================] - 25s 9ms/step - loss: 0.0011 - accuracy: 0.0000e+00
Epoch 2/2
2493/2493 [==============================] - 23s 9ms/step - loss: 6.4019e-04 - accuracy: 0.0000e+00


In [159]:
model.evaluate(generatortest)

8569/8569 [==============================] - 40s 5ms/step - loss: 2.8232e-04 - accuracy: 0.0000e+00


[0.000282318884273991, 0.0]

In [160]:
model.predict(generatortest)

8569/8569 [==============================] - 39s 5ms/step


array([[0.25608912, 0.2559701 , 0.2560467 , 0.25641084, 0.25588322],
       [0.25378296, 0.25425962, 0.2537671 , 0.254165  , 0.25298834],
       [0.25101727, 0.25162625, 0.25093064, 0.25150493, 0.24978887],
       ...,
       [0.4349336 , 0.43590873, 0.43453178, 0.43591836, 0.43273374],
       [0.4240144 , 0.425051  , 0.42347977, 0.4250159 , 0.4213755 ],
       [0.4221429 , 0.42269212, 0.4217048 , 0.42309418, 0.42030472]],
      dtype=float32)

# USING GRU

In [162]:
#tanh in time series,
model=Sequential()
model.add(GRU(units=100,input_shape=(n_input,n_features),activation='tanh'))
model.add(Dense(units=5,activation='tanh'))

In [164]:
model.summary()


Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_1 (GRU)                 (None, 100)               30900     
                                                                 
 dense_10 (Dense)            (None, 5)                 505       
                                                                 
Total params: 31405 (122.68 KB)
Trainable params: 31405 (122.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [165]:

model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [166]:
model.fit(generatortrain,epochs=2)
#y=output(class/labl)

Epoch 1/2
2493/2493 [==============================] - 25s 9ms/step - loss: 0.0012 - accuracy: 0.0000e+00
Epoch 2/2
2493/2493 [==============================] - 22s 9ms/step - loss: 5.8487e-04 - accuracy: 0.0000e+00


In [167]:
model.evaluate(generatortest)

8569/8569 [==============================] - 43s 5ms/step - loss: 2.2782e-04 - accuracy: 1.1670e-04


[0.00022781561710871756, 0.00011669973173411563]

In [ ]:
model.predict(generatortest)